# Generated by Django 4.2.6 on 2023-11-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
