# Generated by Django 4.2.6 on 2023-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('recycling_type', models.CharField(choices=[('Макулатура', 'Waste Paper'), ('Металлолом', 'Scrap Metal'), ('Аккумуляторы', 'Accumulators'), ('Одежда', 'Cloth'), ('Батарейки', 'Batteries'), ('Пластик', 'Plastic'), ('Стеклотара', 'Glass Containers'), ('Техника', 'Technique')], max_length=100, verbose_name='Тип переработки')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('district', models.CharField(choices=[('Советский', 'Soviet'), ('Приволжский', 'Privolzhsky'), ('Вахитовский', 'Vakhitovsky'), ('Московский', 'Moscow'), ('Авиастроительный', 'Aircraft Manufacturing'), ('Ново - Савиновский', 'Novo Savinovsky')], max_length=70, verbose_name='Район')),
                ('latitude', models.FloatField(verbose_name='Ширина')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
