# Generated by Django 4.2.6 on 2023-11-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shop_likeshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recyclingcenter',
            options={'verbose_name': 'Центр переработки', 'verbose_name_plural': 'Центры переработки'},
        ),
        migrations.DeleteModel(
            name='LikeShop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
