# Generated by Django 4.2.6 on 2024-04-15 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_recyclingcenter_options_delete_likeshop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesRecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('recycling_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_center', to='main.recyclingcenter', verbose_name='Центр переработки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_center', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'favorites_center',
                'ordering': ('-time_create',),
                'indexes': [models.Index(fields=['-time_create'], name='favorites_c_time_cr_11a660_idx')],
                'unique_together': {('recycling_center', 'user')},
            },
        ),
    ]
