# Generated by Django 4.2.6 on 2023-10-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('adres', models.TextField(verbose_name='Адрес')),
                ('timejob', models.TextField(verbose_name='График работы')),
            ],
        ),
    ]
