# Generated by Django 4.2.6 on 2023-11-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_ratingstore_alter_likestore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likestore',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добавления'),
        ),
    ]
