# Generated by Django 4.2.6 on 2023-11-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_likestore_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/stores_pictures', verbose_name='Фото'),
        ),
    ]
