# Generated by Django 4.2.6 on 2023-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_articles_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_create'], 'verbose_name': 'Комментарий новости', 'verbose_name_plural': 'Комментарии новости'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(max_length=3000, verbose_name='Описание'),
        ),
    ]
