# Generated by Django 4.2.6 on 2023-11-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_comment_options_alter_articles_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles_pictures', verbose_name='Фото'),
        ),
    ]
