# Generated by Django 4.2.6 on 2023-11-30 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_articles_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_event', to='forum.articles', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_event', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохранение события',
                'verbose_name_plural': 'Сохраненные события',
                'db_table': 'save_event',
                'ordering': ('-time_create',),
                'indexes': [models.Index(fields=['-time_create'], name='save_event_time_cr_5a05ae_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
